name: workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Test Backend
        working-directory: cron-backend
        run: |
          npm install
          npm test
        env:
          USE_CLUSTER: false
          REDIS_HOST: localhost
          REDIS_PORT: 6379

      - name: Install and Test Frontend
        working-directory: cron-frontend
        run: |
          npm install
          npm test

      - name: Build Frontend
        working-directory: cron-frontend
        run: npm run build

      - name: Install and Test Notification Service
        working-directory: notification-service
        run: |
          npm install
          npm test

      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3

      - name: Build with Docker
        if: github.ref == 'refs/heads/master'
        run: docker compose build

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy
        run: echo "Ready to deploy!"
